apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
  labels:
    name: kubia-liveness
spec:
  containers:
  - name: kubia
    image: mkbarry/kubia-unhealthy
    livenessProbe:
        httpGet:
          path: /
          port: 8080