apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-app
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      name: kubia-app
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia-app
          image: mkbarry/kubia
          ports:
            - containerPort: 8080
